import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt, numpy as np, os
from matplotlib.patches import FancyArrowPatch
out = os.path.join(os.path.dirname(__file__), "..", "figures", "b-one-photon.png")
plt.rcParams.update({"font.size": 11})
r = np.linspace(0, 2, 2001); V = np.abs(np.sinc(2*r))
fig, ax = plt.subplots(figsize=(7, 4.2))
ax.plot(r, V, "k-", lw=2)
ax.axvline(0.5, ls=":", color="gray")
ax.plot(0.5, 0, "o", ms=7, mfc="white", mec="k"); ax.annotate("first zero\nd = λ/2", (0.5, 0), (0.56, 0.62), arrowprops=dict(arrowstyle="->"))
ax.plot(0.715, 0.217, "s", ms=7, color="k"); ax.annotate("weak revival\nd ≈ 0.72λ, V ≈ 0.22", (0.715, 0.217), (0.9, 0.36), arrowprops=dict(arrowstyle="->"))
ax.fill_between(r[r < 0.5], 0, V[r < 0.5], color="0.85", hatch="//", edgecolor="0.6", lw=0)
ax.text(0.03, 0.35, "V > 0: photon cannot\nfully tell paths apart", fontsize=9)
ax.set_xlabel("path separation at scattering, d / λ (photon wavelengths)")
ax.set_ylabel("stripe visibility / visibility with laser off")
ax.set_xlim(0, 2); ax.set_ylim(0, 1.05)
ax.set_title("One scattered photon, isotropic emission: V = |sin(2πd/λ)/(2πd/λ)|", fontsize=11)
# inset schematic
ins = fig.add_axes([0.66, 0.58, 0.3, 0.27]); ins.set_xlim(0, 10); ins.set_ylim(0, 6); ins.axis("off")
ins.plot([0, 10], [2, 2], "b-", lw=2); ins.plot([0, 10], [4, 4], "b-", lw=2)
ins.text(0.1, 4.3, "path 1", fontsize=8, color="b"); ins.text(0.1, 1.2, "path 2", fontsize=8, color="b")
ins.annotate("", (8.8, 2), (8.8, 4), arrowprops=dict(arrowstyle="<->")); ins.text(9.0, 2.8, "d", fontsize=9)
ins.fill_between([4.3, 5.2], 0, 6, color="orange", alpha=0.35); ins.text(3.6, 5.3, "laser", fontsize=8)
ins.annotate("", (7.2, 5.9), (4.75, 4), arrowprops=dict(arrowstyle="->", ls="--", color="r"))
ins.annotate("", (2.0, 0.1), (4.75, 2), arrowprops=dict(arrowstyle="->", ls="--", color="r"))
ins.text(5.6, 5.2, "photon", fontsize=8, color="r"); ins.text(0.2, 0.2, "or from here", fontsize=7, color="r")
ins.text(0, -0.9, "schematic, not to scale", fontsize=7, style="italic")
fig.text(0.01, 0.005, "A real dipole emission pattern changes the details, not the half-wavelength scale; 1995 data spanned d = 0 to ~2λ.", fontsize=8)
fig.tight_layout(rect=(0, 0.03, 1, 1)); fig.savefig(out, dpi=150); print("saved", out)
